name: Build and Push NGINX Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-app:${{ github.sha }}

      - name: Install Expect
        run: sudo apt-get install -y expect

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          PORT: ${{ secrets.PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          expect -c "
          set timeout -1
          spawn ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p $PORT $SSH_USERNAME@$SERVER_IP
          expect \"$ \"
          send \"sudo docker pull $DOCKER_USERNAME/nginx-app:$GITHUB_SHA\r\"
          expect \"$ \"
          send \"sudo docker stop nginx-app || true\r\"
          expect \"$ \"
          send \"sudo docker rm nginx-app || true\r\"
          expect \"$ \"
          send \"sudo docker run -d --name nginx-app --restart unless-stopped -p 8080:80 $DOCKER_USERNAME/nginx-app:$GITHUB_SHA\r\"
          expect \"$ \"
          send \"exit\r\"
          interact
          "
