name: Build and Push NGINX Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-app:${{ github.sha }}

      # Deployment Step: SSH into server and deploy
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # If your SSH key has a passphrase, include this line:
          # passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-app:${{ github.sha }}
            docker stop nginx-app || true
            docker rm nginx-app || true
            docker run -d --name nginx-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/nginx-app:${{ github.sha }}
