name: Build, Save, and Transfer NGINX Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-app:${{ github.sha }} .

      - name: Save Docker Image as TAR
        run: |
          docker save -o nginx-app.tar ${{ secrets.DOCKER_USERNAME }}/nginx-app:${{ github.sha }}

      - name: Transfer Docker Image to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH }}
          port: ${{ secrets.VPS_PORT }}
          source: "nginx-app.tar"
          target: "/tmp/nginx-app.tar"

      - name: Install Expect
        run: sudo apt-get install -y expect

      - name: Load and Deploy Docker Image on Server
        env:
          SERVER_IP: ${{ secrets.VPS_HOST }}
          PORT: ${{ secrets.VPS_PORT }}
          SSH_USERNAME: ${{ secrets.VPS_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH }}
        run: |
          expect -c "
          spawn ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p $PORT $SSH_USERNAME@$SERVER_IP
          expect \"$ \"
          send \"sudo docker load -i /tmp/nginx-app.tar\r\"
          expect \"$ \"
          send \"sudo docker stop nginx-app || true\r\"
          expect \"$ \"
          send \"sudo docker rm nginx-app || true\r\"
          expect \"$ \"
          send \"sudo docker run -d --name nginx-app --restart unless-stopped -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/nginx-app:${{ github.sha }}\r\"
          expect \"$ \"
          send \"exit\r\"
          interact
          "
